title:            Rei
description:      A web developer.
url:              http://chloerei.com
baseurl:          /writings
signoff:          Rei
disqus_shortname: chloerei
google_analytics_id: UA-2196462-6

links:
  - name:         关于
    url:          /about/
  - name:         联系
    url:          /contact/
  - name:         Feed
    url:          /feed.xml
  - name:         Twitter
    url:          https://twitter.com/chloerei
    external:     true
  - name:         GitHub
    url:          https://github.com/chloerei
    external:     true

pygments:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:     [autolink, tables]
